### ISSUE TITLE
Similar project.

### ISSUE THREAD

**Issue by DylanPiercey** [delvedor/Tyval#1]
Hey, a year or so ago I made a similar project. I threw in all the useful validators and regex's I could find, you may find some useful to add to this lib.

[The Project](https://github.com/DylanPiercey/the) -> [The Validators](https://github.com/DylanPiercey/the/tree/master/lib/test)

Feel free to close this issue. 😄

**Comment by delvedor** [comment]
Thanks a lot! 😄 
If you want to contribute PR are welcome!
